### PR TITLE
Try to load bcrypt for hashing of application secrets, but add fallback.

### LINKED ISSUE #1190: bcrypt gem is required explicitly in 5.1.0.rc version
### Steps to reproduce

Install new version of doorkeeper - `gem "doorkeeper", "5.1.0.rc1"`

### Expected behavior

Application works and bcrypt is either not required or added as a dependency.

### Actual behavior

```
LoadError: cannot load such file -- bcrypt
```

### PR DESCRIPTION
**Pull request by oliverguenther**
Currently bcrypt was an implicit dependency of the token hashing added to bcrypt without explicitly adding it to the gemspec.

Since bcrypt hashing on applications was merely a choice without much implied security, we should not push this requirement on all users of doorkeeper.

Instead, this PR will try to configure `Doorkeeper::Application` with bcrypt secret hashing and fall back to the default SHA256 digest if it was not found.

A documentation section was added to the README that introduces token hashing and also documents how to add bcrypt.

Fixes #1190

### CODE REVIEW

File: spec/support/shared/hashing_shared_context.rb [hunk 1]
```diff
@@ -25,5 +25,7 @@
     Doorkeeper.configure do
       hash_application_secrets
     end
+
+    ::Doorkeeper::Application.set_bcrypt_hashing_if_available
```
Comment (nbulaj) [inline spec/support/shared/hashing_shared_context.rb]: Why do we need to manually call it in the specs?

File: lib/doorkeeper/models/application_mixin.rb [hunk 2]
```diff
@@ -12,19 +10,7 @@ module ApplicationMixin
...
-
-      # Also need to override the comparer function for BCrypt
-      self.secret_comparer = lambda do |plain, secret|
-        begin
-          BCrypt::Password.new(secret.to_s) == plain.to_s
-        rescue BCrypt::Errors::InvalidHash
-          false
-        end
-      end
+      set_bcrypt_hashing_if_available
```
Comment (nbulaj) [inline lib/doorkeeper/models/application_mixin.rb]: I prefer to use something more abstract, like `configure_secrets_hashing`, because we can replace bcrypt or add other engines for hashing, and the name of the method ceases to comply with the purposes.

File: spec/support/shared/hashing_shared_context.rb (hunk 1 above)
Comment (oliverguenther) [reply spec/support/shared/hashing_shared_context.rb]: The include happens one time when the model is loaded, which with random order will happen anywhere in the specs. If I stub the availibility of bcrypt in the one spec and would not reset it in the next one, the spec will end up running the non-bcrypt configured application model.

File: lib/doorkeeper/models/application_mixin.rb (hunk 2 above)
Comment (oliverguenther) [reply lib/doorkeeper/models/application_mixin.rb]: Yes, good point!

File: spec/support/shared/hashing_shared_context.rb (hunk 1 above)
Comment (nbulaj) [reply spec/support/shared/hashing_shared_context.rb]: Ahh, OK, I got it. That's OK

**Comment by nbulaj** [comment]
@oliverguenther don't forget to add an entry to NEWS.md please :)

**Comment by nbulaj** [comment]
Ping @oliverguenther :)

**Comment by oliverguenther** [comment]
Thanks @nbulaj for the ping, was on sick leave yesterday and only sifting through my mails now. Added the news entry.

File: NEWS.md [hunk 3]
```diff
@@ -7,7 +7,8 @@ User-visible changes worth mentioning.
 
 ## master
 
-- [#] Add your PR description here.
+- [#1191]: Try to load bcrypt for application hashing, but add fallback.
```
Comment (nbulaj) [inline NEWS.md]: Maybe `secrets` instead of `application` ?

Comment (oliverguenther) [reply NEWS.md]: Good point. I changed it to `Try to load bcrypt for hashing of application secrets, but add fallback.` to make sure its clear its related to hashing of the application secrets. Does that fit?

Comment (nbulaj) [reply NEWS.md]: Yep, it's ok, thanks

**Comment by donbobka** [comment]
@nbulaj @oliverguenther May be I'm a little bit late, but I think here too much magic and it can bring  non-obvious side effects to users. It's better to explicitly configure hash algorithm.

Let's imagine I have a project with `doorkeeper` without dependecy by `bcrypt` gem in my Gemfile.lock . I deployed to production and now I have few records that hashed with SHA. 
After that i added gem with `bcrypt` dependency in it (for example `has_secure_password`). This will broke old records, because now `doorkeeper` uses `bcrypt`.

**Comment by nbulaj** [comment]
Well, sounds reasonably. My first thought about configurable hashing wasn't so bad.

I think that we definitely need to introduce a configuration option for hashing. And it must be something like `:sha256` by default and use current behavior. If developer changes it to `:bcrypt`, for example, then it need to use another hasher. I'm for implementing it in a generic way, like it's done for TokenGenerator or ORM extension (I mean I prefer to introduce this configuration in a such way that everybody can define it's own hashing class and use it for Doorkeeper).

@oliverguenther  @donbobka WDYT?

**Comment by oliverguenther** [comment]
Thanks @donbobka for spotting that. Indeed the bcrypt requirement was only added late to the PR and not exactly what I wanted in the first place. Since the hashing function and comparer can be overriden, it would be sane to use SHA256 by default and allow users to define `bcrypt`. But that would be a breaking change - which might be fine in the RC release?

**Comment by nbulaj** [comment]
> Since the hashing function and comparer can be overriden, it would be safe to use SHA256 by default and allow users to define `bcrypt`, we could extend the readme for that

Don't sure I understood, but how overriding of the hashing function will protect from already hashed values ? Somebody used Doorkeeper with default sha for a time, and then decided to add `has_secure_password` for some model, and used `bcrypt`. And Doorkeeper hashing will fallback to bcrypt while already existing tokens / secrets will be invalid.

**Comment by oliverguenther** [comment]
It is clear that we should not decicde on using bcrypt just because it is loaded. But we can either:

1. Let the user configure bcrypt on its own using the existing `hashing_comparer` and `hashing_functions` override of the application class
2. Add a configuration option something along the lines of `use_bcrypt_for_application_secrets_hashing` that actively enables bcrypt.

**Comment by nbulaj** [comment]
> `use_bcrypt_for_application_secrets_hashing` that actively enables bcrypt

As I said, I'm for having an ability to configure full stack of hashing. I mean that in my vision it must be something like:

```ruby
Doorkeeper.configure do
  # enable_hashing - configuration option with it's own options
  enable_hashing using: '::Doorkeeper::Hashing::SHA256' # default behavior
end

# or in case I wanna to use BCrypt

Doorkeeper.configure do
  enable_hashing using: '::Doorkeeper::Hashing::BCrypt'
end
```

Where `Doorkeeper::Hashing::SHA256` is a standalone class that implements all the desired behavior. In this case we can provide two default hashing classes (SHA256 and BCrypt) and any desirable extensions that wouldn't be a part of the core gem (I totally against bloated gems). More of that, nobody will need to "patch" the model to introduce it's own hashing functions - instead they will need to create just one more class, responsible for hashing (model don't need to know about such things imho). And it would be much easier to reuse somebody solution (add gem to your Gemfile and change configuration variable to `Doorkeeper::Hashing::SomeCoolHashingAlgorithm` instead of copy-pasting pieces of code from the GitHub gist to `lib/doorkeeper/models/application.rb`)

**Comment by oliverguenther** [comment]
I'm going to propose a PR soon that implements the `using: ...` syntax. However it should be clear that changing the hashing implementation invalidates all previous secrets. This is especially important for application secrets.

A mitigation to this would be to allow an array of implementations and upgrade the hash to the first function whenever finding another one. But maybe defer implementation until we see the need for it?
